# Auto set the tab and window titles.
zstyle ':prezto:module:terminal' auto-title 'yes'

# Color output (auto set to 'no' on dumb terminals).
zstyle ':prezto:*:*' color 'yes'

# Setup prompt
zstyle ':prezto:module:prompt' theme 'adam1'

# Set the Prezto modules to load (browse modules).
# The order matters.
zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt' \
  'osx'

# Source Prezto.
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# Golang: initialize GOPATH
export GOPATH=$HOME/Projects/Go
export PATH=$GOPATH/bin:$PATH
